### PR TITLE
Add Sina Khalili student page and homework1

### PR DESCRIPTION
**Pull request by SinaKhalili**

### CODE REVIEW

**Review by please-wait — CHANGES_REQUESTED** [review]
@SinaKhalili please fix these:

* Homework name must be `index.ipynb`
* your profile photo must be square shaped (1:1 aspect ratio)

**Comment by SinaKhalili** [comment]
Done 👍 Also 😂 at your github name

**Review by please-wait — APPROVED** [review]

**Comment by please-wait** [comment]
@SinaKhalili your photo name and folder name don't match. Please fix it and send another request.

**Comment by SinaKhalili** [comment]
👍

**Pull request merged**
