### PR TITLE
First hw, bio and profile

### PR DESCRIPTION
**Pull request by rorycochrane**

### CODE REVIEW

**Comment by please-wait** [comment]
@rorycochrane can you please crop your profile photo to a square (1:1 aspect ratio) and convert it to `jpg` instead of `png`?

**Review by please-wait — CHANGES_REQUESTED** [review]
profile photo to 1:1 and `jpg`

**Comment by rorycochrane** [comment]
Sorry for the late response. I made the changes, not sure if I need to make another attempt at merging or something. Please let me know if there's anything more I need to do.

**Comment by please-wait** [comment]
It's ok now. Should work nicely 👍

**Pull request merged**
